version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chimchar-postgres
    environment:
      POSTGRES_DB: chimchar-docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5421:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d chimchar-docker']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chimchar_network

  redis:
    image: redis:7
    container_name: chimchar-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass local --databases 16
    networks:
      - chimchar_network

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=local
      - DATABASE_URL=postgres://admin:admin@db:5432/chimchar-docker
      - REDIS_URL=redis://:local@redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - chimchar_network

volumes:
  postgres_data:
  redis_data:

networks:
  chimchar_network:
    driver: bridge
