services:
  db:
    image: postgres:15
    container_name: chimchar-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chimchar-docker
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d chimchar-docker']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chimchar_network

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/chimchar-docker
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - chimchar_network

volumes:
  postgres_data:

networks:
  chimchar_network:
    driver: bridge
