name: Deploy API

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy to production'
        required: true
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint -- --max-warnings 0 || true

  deploy-staging:
    needs: lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Render CLI
        run: curl -o- https://render.com/download/install.sh | bash

      - name: Deploy to Render (Staging)
        run: |
          render-cli deploy ${{ secrets.RENDER_STAGING_SERVICE_ID }} --token ${{ secrets.RENDER_API_KEY }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

  deploy-production:
    needs: [lint, deploy-staging]
    if: github.event.inputs.deploy_to_production == true
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Render CLI
        run: curl -o- https://render.com/download/install.sh | bash

      - name: Deploy to Render (Production)
        run: |
          render-cli deploy ${{ secrets.RENDER_PRODUCTION_SERVICE_ID }} --token ${{ secrets.RENDER_API_KEY }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} 