name: Run Lint and Format Check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'staging/**'
      - 'production/**'
  pull_request:
    branches: [main]

# Cancel any previous runs in progress
concurrency:
  group: ci-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Formatting and Linting
        run: npm run fix

      - name: Check if files were modified
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Files were modified by the linter. Please commit these changes."
            git diff
            exit 1
          fi
